### ISSUE TITLE
Provide last few lines of output when inflight command stalls

### ISSUE THREAD

**Issue by tynin** [radssh/radssh#15]
Currently, if you issue a command when connected to a bunch of nodes, often you are met with a wall of text. Some of the time most of the nodes finish the command as expected, but a few may not have and appear to be stalled. Presently, if I try to scroll back to find out where they got hung, something forces the screen to go back down to the bottom so I cannot go back and review easily. If I hit CTRL + C, I can see what nodes are the stalled ones, but I have no way of seeing what they were doing. It would be helpful, if on the initial CTRL + C press, if it would give you the last ~3 to ~10 lines (maybe configurable in your .radssh_config file?) so you can be clued in on at least where it hung.

**Comment by radssh** [comment]
Unfortunately, this is not readily attainable under the current architecture. The main (shell) thread that handles KeyboardInterrupt is able to see the list of pending (in-flight) jobs that have not yet completed, but is not able to see the output of the job; but this is only because the main thread keeps a list of the pending jobs, and pops them from the list as they complete. The threads running the jobs are collecting the stdout/stderr in their own private StreamBuffer objects, and only upon completion send the return code (result) that includes the accumulated buffer from the StreamBuffer object. 

Without the process completion, the main thread would need to have a way to access the StreamBuffer object owned by a different thread in order to "see" the stdout/stderr buffers to get access to this data. It might be attainable to patch the Console object itself to keep a dequeue object per source to allow retrieval of the last few lines per host, but that in itself seems a bit expensive for the use case.

**Comment by tynin** [comment]
I tried out the new version with stalled_job_buffer=5. So far so great. Thank you!

**Comment by radssh** [comment]
Including in 1.0.6
