### ISSUE TITLE
Issue with parsing keys?

### ISSUE THREAD

**Issue by Mudpuppy12** [radssh/radssh#20]
Having some weird random host verification key issues. Seem random on each run

Connecting to 10 hosts...
Unable to verify host key for 10.240.0.87
RequirementParseError('Invalid requirement, parse error at "\'\'"',)
Connection to 10.240.0.87 closed.
OUnable to verify host key for 10.240.0.89
RequirementParseError('Invalid requirement, parse error at "\'\'"',)
Connection to 10.240.0.89 closed.
Unable to verify host key for 10.240.0.78
RequirementParseError('Invalid requirement, parse error at "\'\'"',)
Connection to 10.240.0.78 closed.
.OOUnable to verify host key for 10.240.0.69
RequirementParseError('Invalid requirement, parse error at "\'\'"',)
Connection to 10.240.0.69 closed.
O....O
There were problems connecting to some nodes:
    1 nodes failed authentication
    4 dropped connections
    Use "*info" for connection details.
RadSSH $ *exit

root@578160-infra01:~# radssh
Connecting to 10 hosts...
.....O....
There were problems connecting to some nodes:
    1 nodes failed authentication
    Use "*info" for connection details.
RadSSH $ 

This is expected, 1 host did not have a key pushed.

ubuntu 14.04.3 LTS
root@578160-infra01:~# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by Mudpuppy12** [comment]
pip install cryptography==1.2.1 fixed the problem. The latest release breaks things pretty oddly.

**Comment by radssh** [comment]
Is this with the Paramiko 2.0 update(?), which is probably where the cryptography package dependency got introduced. I'm in the process of adding the RadSSH changes to use cryptography instead of PyCrypto, although I only use it directly for the PKCS encrypt/decrypt of passwords.

Also in the soon to be released RadSSH 1.1 is an overhaul of the known_hosts checking, primarily for performance reasons when known_hosts includes a few thousand entries. It does still leverage the Paramiko (and underlying crypto module) for the key loading, so it sounds like it would be impacted by cryptography package, but only if on Paramiko 2.0
