### ISSUE TITLE
config add to default PATH

### ISSUE THREAD

**Issue by mckellyln** [radssh/radssh#41]
I cannot find cmds in /usr/sbin via radssh.
But if I *tty to a machine then my dot files add this to my path and cmds are found.
Is there a way to add /usr/sbin (or any path) to the default path for radssh commands

**Comment by radssh** [comment]
Normal command execution under radssh shell does not source your login scripts, since it does not invoke a login shell (whereas *tty does). Most configurations of bashrc test right at the beginning to see if the shell is interactive (radssh shell is not), and short-circuits most/all of the processing like appending to $PATH.

Radssh does not have direct control over the remote shell environment, but I can see where this would be extremely helpful to do, as updating all remote .bashrc (or such) files is not a good solution. On the other hand, unilaterally attempting to alter PATH seems more dangerous, and possibly counterproductive (Cisco/iDRAC shells probably would reject bash syntax).

I will see if I can come up with something that can work cleanly for this use case. Thanks for the report.

**Comment by radssh** [comment]
Inspired by your own *cd contribution, this looks like a today fit for the same command_listener hook for plugins. Needs some polish and testing, but as a first cut, this seems to offer a decent fix:

```
# Keep path elements as list
add_paths = []
  
def init(**kwargs):
    # Pull the defined dirs from the config setting
    add_paths.extend(kwargs['defaults'].get('plugins.setpath.dirs').split(':'))

def command_listener(cmd):
    # Munge the path setting if we have additional dirs as a prefix to 
    # the command line, as entered.
    if (add_paths):
        return 'PATH=${PATH}:%s; %s' % (':'.join(add_paths), cmd)
```

Put that as a `setpath.py` file in your user plugins directory, and set `plugins.setpath.dirs` in your .radssh_config to `/sbin:/usr/sbin` and see if that works for your environment.

**Comment by mckellyln** [comment]
@radssh works great, thanks.  I did make one change to setpath.py to not issue cmd if it was empty (as in <cr> typed)
```
if (cmd and add_paths):
        return 'PATH=${PATH}:%s; %s' % (':'.join(add_paths), cmd)
```

**Comment by mckellyln** [comment]
@radssh but does this interfere with the command_listener I have for *cd ?

**Comment by mckellyln** [comment]
@radssh I combined my star_cd and setpath into a single plugin file that handles both.

**Comment by mckellyln** [comment]
Here is combined plugin text for reference:
```
#
# Copyright (c) 2017 LexisNexis Risk Data Management Inc.
#
# This file is part of the RadSSH software package.
#
# RadSSH is free software, released under the Revised BSD License.
# You are permitted to use, modify, and redsitribute this software
# according to the Revised BSD License, a copy of which should be
# included with the distribution as file LICENSE.txt
#
import os

curr_dir = ''

# Keep path elements as list
add_paths = []

def init(**kwargs):
    # Pull the defined dirs from the config setting
    add_paths.extend(kwargs['defaults'].get('plugins.setpath.dirs').split(':'))

def star_cd(cluster, logdir, cmd, *args):
    '''global chdir (prepends to all cmds)'''
    global curr_dir
    if not args:
        curr_dir = ''
        return
    if os.path.isabs(args[0]) or args[0].startswith('~'):
        curr_dir = args[0]
        return
    curr_dir = os.path.join(curr_dir, args[0])

star_commands = {'*cd': star_cd}

def command_listener(cmd):
    if (curr_dir and cmd and cmd[0] != '*'):
        if (add_paths):
            return 'cd %s ; PATH=${PATH}:%s ; %s' % (curr_dir, ':'.join(add_paths), cmd)
        return 'cd %s ; %s' % (curr_dir, cmd)
    if (add_paths and cmd and cmd[0] != '*'):
        return 'PATH=${PATH}:%s; %s' % (':'.join(add_paths), cmd)
```

**Comment by mckellyln** [comment]
@radssh I think we can close this issue now.
