### ISSUE TITLE
Whoa There Cowboy! doesn't activate for rm when doing a loop

### ISSUE THREAD

**Issue by hsmalley** [radssh/radssh#60]
```
RadSSH $ for x in $(cat /etc/redhat-release | grep 6.10); do rm -f /etc/cron.daily/clamdscan.sh; done
Average completion time for 11 hosts: 0.073317s
RadSSH $ rm .test
STOP! "rm" is listed as a restricted command (Potentially dangerous)
and requires explicit confirmation before running.
Please double check all parameters, just to be sure...
   >>> rm .test
Enter '100%' if completely sure:
```

**Comment by mckellyln** [comment]
Whats in your config .radssh_config for commands.restricted ?
  commands.restricted=reboot,shutdown,halt,poweroff,telinit
try setting it to not have rm in it ?

**Comment by radssh** [comment]
There is intentionally very minimal scanning of the command line from the RadSSH prompt before it gets passed through to the `exec_command` call for each active connection in the cluster. This is because it does not really know if the remote connection interpreter is bash (zsh, ksh, csh, tcsh, sh) or Cisco iOS, or Dell racadm (or similar). The simplistic preprocessing just consists of 3 basic steps:
 - Do a simple string replacement (variable substitution)  replacing  %NAME% to the value of NAME. I did not make this Unix-shell like with $NAME, to allow leveraging the remote shell to perform this. Future enhancement (at some point) is to allow user-config setting to control the format (regex) for what pattern should be used to trigger this find/replace, along with more robust handling of user/host/session variables
 - If the first non-blank character of the entered command line starts with "*", route the command execution to a local *command plugin for processing, instead of sending the entered (and possibly substituted) command line to the remote hosts.
 - Check to see if the first word of the command line is listed in either user-configurable list of commands.restricted or commands.forbidden. The default configuration has a basic representative set to try to safeguard against the user forgetting that they might be doing something across several hundred hosts concurrently, instead of the norm of one ssh session. shutdown, reboot, and removing files (wild carded or not) are included in the restricted command set. These will trigger the user prompt, which is intentionally safeguarded against muscle-memory taking over and typing Y+Return. The forbidden commands include vi, emacs, ssh, which in theory could have some contrived use case to support, seem to be nothing more than a footgun waiting to happen.

In your case, the command that is in scope is "for", so no special safeguard is triggered. If you are expecting the preprocessor to do full bash syntax parsing and analysis, that would be a neat application for a plugin to handle, but then that would open the doors for variations like zsh syntax plugins, iOS syntax plugins, etc.

As far as the workflow to (probably) get you closer to what you want:
- Avoid the for loop.  This actually winds up invoking a for loop on all the remote host interpreters.
- Instead, invoke `grep 6.10 /etc/redhat-release` to identify the subset of actual target servers
- invoke `*noerr` to (temporarily) make that the active set
- invoke your `rm` command, which will only get dispatched to the current active set
- proofread carefully to make sure you didn't anything out
- respond "100%" to confirm that you really do want to remove the file(s)
- Optionally, do more manual commands targeting your 6.10 subset of hosts
- invoke `*enable` to flip back to your entire session cluster as the active set
